import type { Metadata } from "next";
import "./globals.css";
import { FormProvider } from "../Context/FormContext.";
import { StepProvider } from "../Context/StepContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white md:bg-lightGray">
        <StepProvider>
          <FormProvider>{children}</FormProvider>
        </StepProvider>
      </body>
    </html>
  );
}
